#### Perform the following operations on an array of mobile phones prices 6999, 7500,11999, 27899, 14999, 9999.
1. Create a 1d-array of mobile phones prices
2. Convert this array to float type
4. Append a new mobile having price of 13999 Rs. to this array
5. Reverse this array of mobile phones prices
6. Apply GST of 18% on mobile phones prices and update this array.
7. Sort the array in descending order of price
8. What is the average mobile phone price
9. What is the difference b/w maximum and minimum price

#### Create a 1d-array of mobile phones prices

In [39]:
import numpy as np

In [40]:
arr=np.array([6999,7500,11999,27899,14999,9999])
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999])

#### Convert this array to float type

In [41]:
arr=arr.astype(float)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

#### Append a new mobile having price of 13999 Rs. to this array

In [42]:
arr=np.append(arr,13999)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

### Reverse this array of mobile phones prices

In [43]:
arr1=arr[::-1]
arr1

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

### Apply GST of 18% on mobile phones prices and update this array

In [44]:
arr3=arr*1.18
arr3

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

### Sort the array in descending order of price

In [45]:
arr=np.sort(arr)[::-1]
arr

array([27899., 14999., 13999., 11999.,  9999.,  7500.,  6999.])

### What is the average mobile phone price

In [46]:
avg=np.average(arr)
avg

np.float64(13342.0)

### What is the difference b/w maximum and minimum price

In [47]:
max_price=np.max(arr)
max_price

np.float64(27899.0)

In [48]:
min_price=np.min(arr)
min_price

np.float64(6999.0)

In [49]:
diff=max_price-min_price
diff

np.float64(20900.0)