### Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,subtraction, multiplication, and division on them.

In [1]:
import numpy as np

In [4]:
arr1=np.arange(1,7).reshape((2,3))
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2=np.arange(10,16).reshape((2,3))
arr2

array([[10, 11, 12],
       [13, 14, 15]])

#### Adition

In [22]:
np.add(arr1,arr2)

array([[11, 13, 15],
       [17, 19, 21]])

In [23]:
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21]])

#### Substraction

In [27]:
np.subtract(arr1,arr2)

array([[-9, -9, -9],
       [-9, -9, -9]])

In [28]:
np.subtract(arr2,arr1)

array([[9, 9, 9],
       [9, 9, 9]])

In [29]:
arr1-arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [30]:
arr2-arr1

array([[9, 9, 9],
       [9, 9, 9]])

#### Multiplication

In [31]:
np.multiply(arr1,arr2)

array([[10, 22, 36],
       [52, 70, 90]])

In [32]:
arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

#### Division

In [33]:
np.divide(arr1,arr2)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [34]:
np.divide(arr2,arr1)

array([[10.  ,  5.5 ,  4.  ],
       [ 3.25,  2.8 ,  2.5 ]])

In [35]:
arr1/arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [36]:
arr2/arr1

array([[10.  ,  5.5 ,  4.  ],
       [ 3.25,  2.8 ,  2.5 ]])