### Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [1]:
import numpy as np

In [3]:
A=np.arange(1,5).reshape((2,2))
A

array([[1, 2],
       [3, 4]])

In [4]:
B=np.arange(5,9).reshape((2,2))
B

array([[5, 6],
       [7, 8]])

#### np.dot()

In [5]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

#### @

In [7]:
A@B

array([[19, 22],
       [43, 50]])