### Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.Explain how broadcasting works in this operation.

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2=np.array([1,2,3])
arr2

array([1, 2, 3])

In [4]:
arr1+arr2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [5]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])