### Find the row-wise and column-wise sums.

In [1]:
import numpy as np

In [5]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
row=np.sum(arr1,axis=1)
row

array([ 6, 15, 24])

In [7]:
column=np.sum(arr1,axis=0)
column

array([12, 15, 18])