### Mathematical Arithmatic Function

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape((3,3))
arr2=np.arange(3,12).reshape((3,3))
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [3]:
np.add(arr2,arr1)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [4]:
arr2+arr1

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [5]:
arr3=np.array([10,20,30])
arr3

array([10, 20, 30])

In [6]:
np.subtract(arr2,arr1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [7]:
arr1-arr2

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

In [8]:
arr1+arr3

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [9]:
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [10]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [11]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [12]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [13]:
np.multiply(arr1,arr2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [14]:
np.divide(arr1,arr2)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [15]:
arr1/arr2

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [16]:
arr1+arr2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [17]:
np.concatenate([arr1,arr2]) #No of columns should be same

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate([arr1,arr2],axis=1) #No of rows should be same

array([[ 1,  2,  3,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11]])

## Spliting

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.split(arr1,3,axis=1) #you can split in equal parts only

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [21]:
arr9=np.arange(1,13).reshape(3,4)
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.split(arr9,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [23]:
np.split(arr9,4,axis=1)


[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [27]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr1.min()

np.int64(1)

In [29]:
arr1.max()

np.int64(9)

In [30]:
arr1.argmax()

np.int64(8)

In [31]:
arr1.argmin()

np.int64(0)

In [32]:
arr2.argmax()

np.int64(8)

In [33]:
arr2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
arr2.argmin()

np.int64(0)

In [35]:
arr2.max()

np.int64(11)

In [36]:
arr2.min()

np.int64(3)