In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr2=np.array([10,3.14,20])
arr2

array([10.  ,  3.14, 20.  ])

In [4]:
arr3=np.array([10,3.14,'s'])
arr3

array(['10', '3.14', 's'], dtype='<U32')

In [5]:
arr4=np.arange(1,11)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr2d=np.arange(1,13).reshape((4,3))
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr2d.ndim

2

In [8]:
arr2d.shape

(4, 3)

In [9]:
arr2d.size

12

In [10]:
arr3d=np.arange(1,25).reshape((2,4,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [11]:
arr4d=np.arange(1,73).reshape((3,2,4,3))
arr4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]],


       [[[25, 26, 27],
         [28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45],
         [46, 47, 48]]],


       [[[49, 50, 51],
         [52, 53, 54],
         [55, 56, 57],
         [58, 59, 60]],

        [[61, 62, 63],
         [64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]]])

In [12]:
type(arr4)

numpy.ndarray

In [13]:
arr4.size

10

In [14]:
arr4.shape

(10,)

In [15]:
arr4.ndim

1

In [16]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [17]:
arr2d[0]

array([1, 2, 3])

In [18]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2d[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
arr3=np.arange(1,43).reshape((6,7))
arr3

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [21]:
arr3[1:4,1:5]

array([[ 9, 10, 11, 12],
       [16, 17, 18, 19],
       [23, 24, 25, 26]])

In [22]:
arr3[:,:-1]

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34],
       [36, 37, 38, 39, 40, 41]])

In [23]:
arr3[:,-1]

array([ 7, 14, 21, 28, 35, 42])

In [24]:
arr3[[0,2,5]]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [36, 37, 38, 39, 40, 41, 42]])

In [25]:
arr3[:,[0,3,4]]

array([[ 1,  4,  5],
       [ 8, 11, 12],
       [15, 18, 19],
       [22, 25, 26],
       [29, 32, 33],
       [36, 39, 40]])

In [26]:
arr=np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
arr1=np.arange(1,49).reshape(4,2,3,2)
arr1

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]],


       [[[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]],


       [[[37, 38],
         [39, 40],
         [41, 42]],

        [[43, 44],
         [45, 46],
         [47, 48]]]])

In [28]:
arr5=np.arange(1,61).reshape(5,3,2,2)
arr5

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]],


       [[[25, 26],
         [27, 28]],

        [[29, 30],
         [31, 32]],

        [[33, 34],
         [35, 36]]],


       [[[37, 38],
         [39, 40]],

        [[41, 42],
         [43, 44]],

        [[45, 46],
         [47, 48]]],


       [[[49, 50],
         [51, 52]],

        [[53, 54],
         [55, 56]],

        [[57, 58],
         [59, 60]]]])