In [1]:
import numpy as np

In [2]:
np.random.random()

0.06852244487927872

In [3]:
team1=np.random.randint(0,36,20)
team1

array([ 6, 20,  0, 35, 19, 20, 12, 22, 35, 35, 28, 20, 11, 12, 31,  7, 30,
        6,  6,  7], dtype=int32)

In [4]:
np.random.randint(0,36,(4,5))

array([[ 4,  9, 31,  2, 35],
       [18, 32,  0,  7,  2],
       [30, 11, 28, 12, 10],
       [26, 18,  2, 23, 28]], dtype=int32)

In [12]:
np.random.seed(50)
np.random.randint(1,100,2)

array([49, 97], dtype=int32)

In [10]:
np.random.rand()

0.8724262944092156

In [8]:
np.random.randn(10)

array([-0.01002595,  1.67080819, -0.66437971, -0.60555494, -0.65099088,
        0.51256776,  0.26238882, -0.58273165,  1.36842193,  0.05336866])

In [13]:
dice=np.arange(1,7)

In [15]:
np.random.choice(dice,1)

array([6])

In [16]:
dice

array([1, 2, 3, 4, 5, 6])

In [20]:
np.random.permutation(dice)

array([1, 3, 2, 6, 4, 5])

In [21]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)

In [23]:
np.cos(np.radians(30))

np.float64(0.8660254037844387)